---
title: "Reproducible documents"
author: "Christine Ljungberg"
format: html
editor: visual
---
- Christine Ljungberg 
- Aauhus University
- Department of Clinical Epidemiology 

# Intro 
Writre one **random** *sentence*. 

# Methods and Results 

## Analysis 
```{r}
2+2
```

# Discussion 


```{r setup}
#|message: false
#|warning: false
library(tidyverse)
library(NHANES)
nhanes_small <- read_csv(here::here("data/NHANES_small.CSV"))
```


```{r}
nhanes_small <- select(nhanes_small, age, sex, bmi, diabetes, phys_active, bp_sys_ave, bp_dia_ave, education)
nhanes_small
```



```{r}
2 + 2
```
# Table of results 

```{r}
nhanes_small %>%
  filter(!is.na(diabetes)) %>%
  group_by(diabetes, education) %>%
  summarise(
    mean_age = mean(age, na.rm = T),
    mean_bmi = mean(bmi, na.rm = T)
  ) %>%
  ungroup() %>%
  knitr::kable(caption = "Mean values of age and BMI for each diabetes status and education level")
```


```{r}
#|echo: false
nhanes_small %>%
  filter(!is.na(diabetes), !is.na(education)) %>%
  group_by(diabetes, education) %>%
  summarise(
    mean_age = mean(age, na.rm = TRUE),
    mean_bmi = mean(bmi, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  mutate(
    mean_age = round(mean_age, 1),
    mean_bmi = round(mean_bmi, 1),
    education = str_to_sentence(education)
  ) %>%
  rename(
    # Task 3.
    "Diabetes status" = diabetes,
    "Education" = education,
    "Mean age" = mean_age,
    "Mean BMI" = mean_bmi
  ) %>%
  knitr::kable(caption = "Mean values of Age and BMI for each education and diabetes status.")
```
